###############################################################################
#   @author         :   Naty Laza
#   @date           :   28/10/2018
#   @package        :   Alexa Anouncment
#   @description    :   Welcome Home, Shopping etc.
###############################################################################

####################################################
#                   Customize                      #
####################################################

homeassistant:
  customize_domain:
    automation:
      initial_state: 'on'
  
  customize:

#Automations
  #Naty     
     automation.alexa_anounced_welcome_naty_home:
      icon: mdi:home-circle
      friendly_name: "Alexa - Welcome Home Naty"
     automation.alexa_anounced_that_naty_at_hazihinam:
      icon: mdi:cart
      friendly_name: "Alexa - Naty at Hazi Hinam"
     automation.alexa_anounced_that_naty_at_shufersal:
      icon: mdi:cart
      friendly_name: "Alexa - Naty at Shufersal"
  #Nofar  
     automation.alexa_anounced_welcome_nofar_home:
      icon: mdi:home-circle
      friendly_name: "Alexa - Welcome Home Nofar"
     automation.alexa_anounced_that_nofar_at_hazihinam:
      icon: mdi:cart
      friendly_name: "Alexa - Nofar at Hazi Hinam"
     automation.alexa_anounced_that_nofar_at_shufersal:
      icon: mdi:cart
      friendly_name: "Alexa - Nofar at Shufersal"

####################################################
#                    Automation                    #
####################################################

automation:

###################
#       Naty      #
###################

- id: Alexa Anounced Welcome Naty Home
  alias: Alexa Anounced Welcome Naty Home
  trigger:
  - entity_id: sensor.naty_current_status
    platform: state
    to: 'home'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: device_tracker.mi_a1
        state: 'home'
      - condition: time
        before: '23:00:00'
        after: '8:00:00'
  action:
  - delay: 00:00:10
  - service: media_player.alexa_tts 
    entity_id: media_player.natys_echo_dot
    data:
        message: "Welcome Home Naaty"

# hezi hinam announcement
- id: Alexa Anounced that Naty at hazihinam
  alias: Alexa Anounced that Naty at hazihinam
  trigger:
  - entity_id: sensor.naty_current_status
    platform: state
    to: 'hazi_hinam'
    for:
     minutes: 15
  condition:
  - condition: state
    entity_id: sensor.nofar_current_status
    state: 'home'
  action:
  - service: media_player.alexa_tts 
    entity_id: media_player.natys_echo_dot
    data:
        message: "Naaty is at Haatzi Heenaame doing shopping"
        
# Shufersal announcement
- id: Alexa Anounced that Naty at shufersal
  alias: Alexa Anounced that Naty at shufersal
  trigger:
  - entity_id: sensor.naty_current_status
    platform: state
    to: 'Shufersal'
    for:
     minutes: 15
  condition:
  - condition: state
    entity_id: sensor.nofar_current_status
    state: 'home'
  action:
  - service: media_player.alexa_tts 
    entity_id: media_player.natys_echo_dot
    data:
        message: "Naaty is at shufersaal doing shopping"  
        
####################
#       Nofar      #
####################

- id: Alexa Anounced Welcome Nofar Home
  alias: Alexa Anounced Welcome Nofar Home
  trigger:
  - entity_id: sensor.nofar_current_status
    platform: state
    to: 'home'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: device_tracker.oneplus_5t
        state: 'home'
      - condition: time
        before: '23:00:00'
        after: '8:00:00'
  action:
  - delay: 00:00:10
  - service: media_player.alexa_tts 
    entity_id: media_player.natys_echo_dot
    data:
        message: "Welcome Home Nofar"

# Nofar at hezi hinam announcement
- id: Alexa Anounced that Nofar at hazihinam
  alias: Alexa Anounced that Nofar at hazihinam
  trigger:
  - entity_id: sensor.nofar_current_status
    platform: state
    to: 'Hazi Hinam'
    for:
     minutes: 15
  condition:
  - condition: state
    entity_id: sensor.naty_current_status
    state: 'home'
  action:
  - service: media_player.alexa_tts 
    entity_id: media_player.natys_echo_dot
    data:
        message: "Nofar is at Haatzi Heenaame doing shopping"
        
# Nofar at shufersal announcement
- id: Alexa Anounced that Nofar at shufersal
  alias: Alexa Anounced that Nofar at shufersal
  trigger:
  - entity_id: sensor.nofar_current_status
    platform: state
    to: 'Shufersal'
    for:
     minutes: 15
  condition:
  - condition: state
    entity_id: sensor.naty_current_status
    state: 'home'
  action:
  - service: media_player.alexa_tts 
    entity_id: media_player.natys_echo_dot
    data:
        message: "Nofar is at shufersaal doing shopping"
