###############################################################################
#   @author         :   Naty Laza
#   @date           :   28/10/2018
#   @package        :   Alexa Configuration
#   @description    :   Cloud Configuration of Alexa
###############################################################################

####################################################
#               Alexa Configuration                #
####################################################
cloud:
  alexa:
    filter:
      include_entities: 
        - alarm_control_panel.home_alarm
        - climate.ac
        - fan.bedroom_fan 
        - light.gateway_light
        - media_player.natys_echo_dot
      include_domains:
        - switch
        - script
        - lights
      exclude_entities:
        - media_player.natys_alexa_apps
        - media_player.this_device
      exclude_domains:
        - device_tracker
        - automation
        - binary_sensor
        - calendar
        - customizer
        - group
        - input_boolean
        - input_select
        - input_text
        - sensor
        - zone
        - sun

#Customize Entities as will be shown in alexa app
    entity_config:
#Bed Room      
      switch.brfan_light:
        name: Fan Light
        description: BR Fan Light Power
      script.bed_room_fan_mode:
        name: Fan Mode
        description: BR Fan Mode
      fan.bedroom_fan:
        name: Bed Room Fan
        description: Bed Room Fan 
#Living Room
      switch.lrac_power:
        name: AC Power
        description: LR AC Power
      switch.lrmibox_power:
        name: Mi Box  
        description: Mi Box Power
      switch.lrtv_mute:
        name: Mute TV
        description: Mute LR TV
      switch.lrtv_power: 
        name: TV
        description: LR TV Power
      switch.lrtv_stripled_power:
        name: Strip Led
        description: LR TV Strip Led Power
      switch.xiaomi_plug: 
        name: Smart Plug 
        description: Xiaomi Smart Plug
      script.lrtv_volume_up:
        name: TV Volume UP               
        description: LR TV Volume UP 
      script.lrtv_volume_down:
        name: TV Volume Down
        description: LR TV Volume Down 
      script.temp_up:
        name: Temp UP
        description: LR AC Temp UP
      script.temp_down:
        name: Temp Down
        description: LR AC Temp
      script.lrmibox3_volume_up:
        name: Mi Box Volume UP
        description: Mi Box Volume UP
      script.lrmibox3_volume_down:
        name: Mi Box Volume Down
        description: Mi Box Volume Down   
      light.gateway_light:
        name: Gateway Light
        description: Gateway Light
      climate.ac:
        name: Living Room AC
        description: Living Room AC
      media_player.natys_echo_dot:
        name: Echo Dot
        description: Echo Dot
 #Alarm Control  
      alarm_control_panel.home_alarm:
        name: Alarm
        description: Alarm
#Work Room
      light.yeelight_white:
        name: Office Light
        description: Office Light