###############################################################################
#   @author         :   Naty Laza
#   @date           :   28/10/2018
#   @package        :   Bed Room Fan
#   @description    :   Fan Settings , Script, Automation etc.
###############################################################################

####################################################
#                   Customize                      #
####################################################

homeassistant:
  customize:
#Fan Bed Room
     switch.brfan_light:
      friendly_name: Light Power
      icon: mdi:ceiling-light
      assumed_state: false
     automation.brfan_input_select_toggle:
      initial_state: 'on'
      icon: mdi:fan
      friendly_name: "Fan Toggle Ability"
      
####################################################
#                    Bed Room Fan                  #
####################################################  

fan:
- platform: broadlink
  name: Bedroom Fan
  host: !secret broadlink_host
  mac: !secret broadlink_mac
  rfcodes_ini: 'custom_components/broadlink_fan_codes/br_fan.ini'
  default_speed: low
  defaut_direction: left
  customize:
      speeds:
            - low
            - medium
            - high
            - highest
    
####################################################
#                      Switch                      #
####################################################

# Broadlink Configuration
switch:  
  - platform: broadlink
    host: !secret broadlink_host
    mac: !secret broadlink_mac
    friendly_name: rm
    type: rm
    timeout: 15
    switches:
#brfan_light     
     brfan_light:
      friendly_name: "Light Power"
      command_on: 'sgo0ACMNIw0kDSMNDCUkDQwlJA0MJSQNDAABcSQNDCUkDSQNJA0kDSQNJA0MJSQNJA0MJSQNDCUAAAAA'
      command_off: 'sgo0ACMNIw0kDSMNDCUkDQwlJA0MJSQNDAABcSQNDCUkDSQNJA0kDSQNJA0MJSQNJA0MJSQNDCUAAAAA'

############################################################
#                         Sensors                          #
############################################################
sensor:
  - platform: template
    sensors:
#Bed Room Fan Light State
       br_fan_light_status:
         value_template: >-
            {% if is_state('switch.brfan_light', 'on') %}
               on
            {% else %}
               off
            {% endif %}
         friendly_name: 'Bedoom Fan Light'  
#Bed Room Fan Power State
       br_fan_status:
         value_template: >-
            {% if is_state('fan.bedroom_fan', 'on') %}
               on
            {% else %}
               off
            {% endif %}
         friendly_name: 'Bedroom Fan'

####################################################
#                  Input Select                    #
####################################################
input_select:
#Bedroom Fan Mode Input Select 
 br_fan:
  name: br_fan
  options:
    - LOW
    - MED

############################################################
#                         Scripts                          #
############################################################
script:
           
#Fan Set Mode Scripts
 brfan_mode_low:
  sequence:
    - service: fan.set_speed
      data_template:
        entity_id: fan.bedroom_fan
        speed: low
 
 brfan_mode_medium:
  sequence:
    - service: fan.set_speed
      data_template:
        entity_id: fan.bedroom_fan
        speed: medium
 
#Fan Toggle Script
 bed_room_fan_mode:
  sequence:
    - service_template: >
          {% if is_state('input_select.br_fan', 'LOW') %} script.brfan_mode_low
          {% elif is_state('input_select.br_fan', 'MED') %} script.brfan_mode_medium
          {% endif %}

####################################################
#                   Automations                    #
####################################################
automation:
#Runs when Input Select get toggeled
- id: brfan_input_select_toggle
  alias: brfan_input_select_toggle
  trigger:
  - platform: state
    entity_id: input_select.br_fan
  action:
  - service: script.bed_room_fan_mode
