###############################################################################
#   @author         :   Naty Laza
#   @date           :   28/10/2018
#   @package        :   influxdb Database , History , Logger, Logbook,
#   @description    :   Database Configuration and History of entities
###############################################################################

recorder:
  purge_interval: 2
  purge_keep_days: 2
  include:
    entities:
       - device_tracker.nl
       - device_tracker.nc
       - device_tracker.mi_a1
       - device_tracker.oneplus_5t
       - device_tracker.x #(arp scan)
       - device_tracker.x #(arp scan)
       - alarm_control_panel.home_alarm
       - fan.bedroom_fan
       - light.gateway_light
       - light.yeelight_white
       - sensor.temperature_bedroom
       - sensor.temperature_kitchen
       - sensor.temperature_livingroom
       - sensor.temperature_workroom
       - sensor.humidity_bedroom
       - sensor.humidity_kitchen
       - sensor.humidity_livingroom
       - sensor.humidity_workroom
       - sensor.nofar_current_status
       - sensor.naty_current_status
    domains:
      - binary_sensor
      - switch
  exclude:
    domains:
      - calendar
      - customizer
      - zone
      - input_select
      - input_boolean
      - input_text
      - automation
      - climate
      - script
      - time
      - sensor
      - group
    entities:
       - sun.sun
####################################################
#                influxdb Database                 #
#################################################### 

influxdb:
  host: !secret influxdb_url
  username: !secret influxdb_username
  password: !secret influxdb_password
  database: home_assistant
  max_retries: 3
  default_measurement: state
  include:
    entities:
       - device_tracker.nl
       - device_tracker.nc
       - device_tracker.mi_a1
       - device_tracker.oneplus_5t
       - device_tracker.x #(arp scan)
       - device_tracker.x #(arp scan)
       - alarm_control_panel.home_alarm
       - fan.bedroom_fan
       - light.gateway_light
       - light.yeelight_white
       - sensor.temperature_bedroom
       - sensor.temperature_kitchen
       - sensor.temperature_livingroom
       - sensor.temperature_workroom
       - sensor.humidity_bedroom
       - sensor.humidity_kitchen
       - sensor.humidity_livingroom
       - sensor.humidity_workroom
       - sensor.nofar_current_status
       - sensor.naty_current_status
    domains:
      - binary_sensor
      - switch
  exclude:
    domains:
      - calendar
      - customizer
      - zone
      - input_select
      - input_boolean
      - input_text
      - automation
      - climate
      - script
      - time
      - sensor
      - group
    entities:
       - sun.sun

####################################################
#                        History                   #
#################################################### 

history:
   include:
    entities:
       - device_tracker.nl
       - device_tracker.nc
       - device_tracker.mi_a1
       - device_tracker.oneplus_5t
       - device_tracker.x #(arp scan)
       - device_tracker.x #(arp scan)
       - alarm_control_panel.home_alarm
       - fan.bedroom_fan
       - light.gateway_light
       - light.yeelight_white
       - sensor.temperature_bedroom
       - sensor.temperature_kitchen
       - sensor.temperature_livingroom
       - sensor.temperature_workroom
       - sensor.humidity_bedroom
       - sensor.humidity_kitchen
       - sensor.humidity_livingroom
       - sensor.humidity_workroom
       - sensor.nofar_current_status
       - sensor.naty_current_status
    domains:
      - binary_sensor
      - switch
   exclude:
    domains:
      - calendar
      - customizer
      - zone
      - input_select
      - input_boolean
      - input_text
      - automation
      - climate
      - script
      - time
      - sensor
      - group
    entities:
       - sun.sun
####################################################
#                       Logger                     #
#################################################### 

logger: 
    default: warn
    logs:
      aiohttp.access: critical
      aiohttp.server: critical
      homeassistant.core: error
      homeassistant.components.automation: warn
      homeassistant.components.binary_sensor: error
      homeassistant.components.climate.nest: warn
      homeassistant.components.device_tracker: error
      homeassistant.components.discovery: warn
      homeassistant.components.http: warn
      homeassistant.components.media_player: warn
      homeassistant.components.sensor.pi_hole: critical
      homeassistant.components.recorder: critical
      homeassistant.components.sensor.darksky: warn
      homeassistant.components.switch.deluge: warn
      homeassistant.components.zwave: warn
      homeassistant.helpers.script: warn
      homeassistant.helpers.entity: critical
      homeassistant.exceptions: info
      py.warnings: error
      root: warn

####################################################
#                       Logbook                    #
#################################################### 

logbook:
   include:
    entities:
       - device_tracker.nl
       - device_tracker.nc
       - device_tracker.mi_a1
       - device_tracker.oneplus_5t
       - device_tracker.x #(arp scan)
       - device_tracker.x #(arp scan)
       - alarm_control_panel.home_alarm
       - fan.bedroom_fan
       - light.gateway_light
       - light.yeelight_white
       - sensor.temperature_bedroom
       - sensor.temperature_kitchen
       - sensor.temperature_livingroom
       - sensor.temperature_workroom
       - sensor.humidity_bedroom
       - sensor.humidity_kitchen
       - sensor.humidity_livingroom
       - sensor.humidity_workroom
       - sensor.nofar_current_status
       - sensor.naty_current_status
    domains:
      - binary_sensor
      - switch
   exclude:
    domains:
      - calendar
      - customizer
      - zone
      - input_select
      - input_boolean
      - input_text
      - automation
      - climate
      - script
      - time
      - sensor
      - group
    entities:
       - sun.sun
################################################################