###############################################################################
#   @author         :   Naty Laza
#   @date           :   12/9/2018
#   @package        :   Lights
#   @description    :   Not in use atm
###############################################################################

####################################################
#                   Customize                      #
####################################################

homeassistant:
  customize:
   
####################################################
#                    Light                         #
####################################################

