######################################################################################
#   @author         :   Naty Laza
#   @date           :   28/10/2018
#   @package        :   Network Services, Frontend(UI)
#   @description    :   Auth,HTTP,FrontEnd,Wake On Lan, DuckDNS,MQTT,Arp-Scan,
#                       Speedtest,Lets Encrypt,Links Pannel,RPI Network Status 
#
######################################################################################

####################################################
#                   Customize                      #
####################################################

homeassistant:
  customize:
#Speed Test  
     sensor.speedtest_download:
      icon: mdi:download
     sensor.speedtest_upload:
      icon: mdi:upload
     sensor.speedtest_ping:
      icon: mdi:console
  customize_glob:
    fan.*:
      custom_ui_state_card: state-card-custom-fanspeed
    switch.brfan_low:
      custom_ui_state_card: state-card-custom-fanspeed
    cover.*:
      custom_ui_state_card: custom-ui

customizer:
  custom_ui: local    
      
####################################################
#                 Authentication                   #
#################################################### 

auth:

####################################################
#                        HTTP                      #
####################################################  

http:
 api_password: !secret api_password
 base_url: !secret base_url
 ssl_certificate: !secret ssl_certificate_dir
 ssl_key: !secret ssl_key_dir
 login_attempts_threshold: 5
 use_x_forwarded_for: True
 trusted_proxies:
  - 127.0.0.1
  - !secret private_lan

####################################################
#               FrontEnd Includes                  #
####################################################  

frontend:
  javascript_version: latest
  extra_html_url:
   - /local/custom_ui/state-card-custom-ui.html
   - /local/custom_ui/state-card-custom-fanspeed.html
  extra_html_url_es5:
   - /local/custom_ui/state-card-custom-fanspeed.html
   - /local/custom_ui/state-card-custom-ui-es5.html

####################################################
#                  Wake On Lan                     #
####################################################  

wake_on_lan:
 mac: !secret broadlink_mac
 
####################################################
#                    DUCK-DNS                      #
####################################################  

duckdns: 
  domain: !secret duckdns_domain
  access_token: !secret duckdns_access_token

####################################################
#                       MQTT                       #
#################################################### 

mqtt:
  broker: !secret broker_ip
  port: !secret mqtt_port
  client_id: home-assistant-1
  username: !secret mqtt_user
  password: !secret mqtt_password
  discovery: true
  discovery_prefix: homeassistant

####################################################
#        Arp Scan Via Device Tracker               #
#################################################### 

device_tracker:
  - platform: arpscan_tracker
    interval_seconds: 15
    consider_home: 60
    track_new_devices: true
     
####################################################
#                      Sensors                     #
####################################################

sensor:

 #- platform: authenticated 
 
 - platform: unifi
   name: unifi
   username: !secret unifi_username
   password: !secret unifi_password
   url: !secret unif_url
   verify_ssl: false

# SSL Certification
 - platform: command_line
   name: SSL cert expiry
   unit_of_measurement: days
   scan_interval: 3600
   command: !secret sensor_ssl_command
   
 - platform: cert_expiry
   host: !secret base_url

# Speedtest & Fastcom
 - platform: speedtest
   minute: 30
   monitored_conditions:
      - ping
      - download
      - upload 
 
 - platform: fastdotcom
   minute:
      - 0
      - 30

#Network 
 - platform: device_status
   scan_interval: 10
   devices:
    internet_connection:
       host: 8.8.8.8
       name: "Internet Connection"
    edge:
       host: !secret router_ip_sensor
       name: "Edge Router Lite"
    uap:
       host: !secret uap_ip_sensor
       name: "Ubiquity Access Point"
    rmpro:
       host: !secret rmpro_ip_sensor
       name: "Broadlink RM Pro"
    rpi3:
       host: !secret rpi3_ip_sensor
       name: "Raspberry Pie 3"
    mibox3:
       host: !secret mibox3_ip_sensor
       name: "Mi Box 3"
    echo_dot:
       host: !secret echo_ip_sensor
       name: "Echo Dot"
    xiaomi_gateway:
       host: !secret gateway_ip_sensor
       name: "Xiaomi Gateway"
