###################################################################################
#   @author         :   Naty Laza
#   @date           :   28/10/2018
#   @package        :   Payments Reminders
#   @description    :   Electricity,Tax,Water,Rent,Gas
###################################################################################

####################################################
#                   Customize                      #
####################################################

homeassistant:
  customize:
    automation.notify_via_telegram_payments_reminder:
     initial_state: 'on'
     icon: mdi:credit-card
     friendly_name: "Payments Notification Via Telegram"
####################################################
#                    Automation                    #
####################################################
automation:

####################################################
#                  Payments Reminder               #
####################################################

- id: Notify Via Telegram Payments Reminder
  alias: Notify Via Telegram Payments Reminder
  trigger:
  - platform: time
    at: '18:00:00'
  condition:
  - condition: template
    value_template: '{{ now().day == 25}}'
  - condition: template
    value_template: '{{ now().day == 30}}'
  action:
  - data_template:
      title: '*Payments Reminder*'
      message: |
        Don't Forget Paying the Bills & Transfer Money to the Shared Acount! 
        Check List:
        - Electricity
        - Tax
        - Water
        - Rent
        - Gas
    service: notify.all


