###############################################################################
#   @author         :   Naty Laza
#   @date           :   04/01/2019
#   @package        :   Living Room Mi Box 3
#   @description    :   Mi Box 3 Configuration
###############################################################################

####################################################
#                   Customize                      #
####################################################

homeassistant:
  customize:
     switch.lrmibox_power:
      friendly_name: "Mi Box Power"
      icon: mdi:power
      assumed_state: false  

     script.lrmibox3_volume_up:
      friendly_name: "Volume Up"
      icon: mdi:volume-plus
      assumed_state: false
     script.lrmibox3_volume_down:
      friendly_name: "Volume Down"
      icon: mdi:volume-minus
      assumed_state: false
     script.lrmibox3_right_arrow:
      icon: mdi:arrow-right-bold-circle
      assumed_state: false
     script.lrmibox3x_left_arrow:
      icon: mdi:arrow-left-bold-circle
      assumed_state: false
     script.lrmibox3_up_arrow:
      icon: mdi:arrow-up-bold-circle
      assumed_state: false
     script.lrmibox3_down_arrow:
      icon: mdi:arrow-down-bold-circle
      assumed_state: false
     script.lrmibox3_ok_button:
      icon: mdi:check-circle
      assumed_state: false
     script.lrmibox3_back_button:
      icon: mdi:backspace
      assumed_state: false
     script.lrmibox3_exit_main_button:
      icon: mdi:close-circle
      assumed_state: false
     script.lrmibox3_info_button:
      icon: mdi:information
      assumed_state: false
      
####################################################
#                      Switch                      #
####################################################

# Broadlink Configuration

switch:  
  - platform: broadlink
    host: !secret broadlink_host
    mac: !secret broadlink_mac
    friendly_name: rm
    type: rm
    timeout: 15
    switches: 
#lrmibox_power
     lrmibox_power:
      friendly_name: "Mi Box Power"
      command_on: 'JgBOACMRFREVMBUwFREVMBURFTAVERUwFTAWAAEnJBAWEBYvFi8VERUwFREVMBURFTAVMBYAASchExMTEzIVMBURFTAVERUwFREWLxQxFwANBQAAAAAAAAAAAAA='
      command_off: 'JgBOACMRFREVMBUwFREVMBURFTAVERUwFTAWAAEnJBAWEBYvFi8VERUwFREVMBURFTAVMBYAASchExMTEzIVMBURFTAVERUwFREWLxQxFwANBQAAAAAAAAAAAAA='
      
############################################################
#                         Sensors                          #
############################################################

sensor:
  - platform: template
    sensors:
#Mi Box 3 Power State
       lr_mibox_status:
         value_template: >-
            {% if is_state('switch.lrmibox_power', 'on') %}
               on
            {% else %}
               off
            {% endif %}
         friendly_name: 'Living Room Mi Box 3'  
         
############################################################
#                          Scripts                         #
############################################################

script:
#Right Arrow    
    lrmibox3_right_arrow:
      sequence:
        - service: switch.broadlink_send_packet_172_16_10_252
          data:
            packet:
              - "JgBOACMSFiQVERUdFCUUExUSFC8VEhUSFSUUAAGuJBEUJhMUEx0UJhUSFBMULxUSFRIVJBUAAa8iEhUkFRIWGxUkFhEWERUuFhEVEhUlFAANBQAAAAAAAAAAAAA="
              
#Left Arrow    
    lrmibox3x_left_arrow:
      sequence:
        - service: switch.broadlink_send_packet_172_16_10_252
          data:
            packet:
              - "JgBOACMSFCYUExUbFCYVEhQSFSUVLhYbFRsWAAGaIxEVJRUSFhoVJRUSFRIVJRQvFRsVHBQAAZwjERUlFhAWGxYkFRIVERUmFC8VGxUcEwANBQAAAAAAAAAAAAA="
              
#Up Arrow    
    lrmibox3_up_arrow:
      sequence:
        - service: switch.broadlink_send_packet_172_16_10_252
          data:
            packet:
              - "JgBOACITFSQWERYaFiQVEhUSFRsWGxQmFC8VAAGaJBEVJRQTFBwVJRQTFREWGxUbFSUULxQAAZ0iERYkFBMVGxYkFRIUExUbFRwVJRUvFAANBQAAAAAAAAAAAAA="
              
#Down Arrow    
    lrmibox3_down_arrow:
      sequence:
        - service: switch.broadlink_send_packet_172_16_10_252
          data:
            packet:
              - "JgBOACMSFSUVEhUbFSYUEhUSFRwUJRQmFRIUAAGvIxEUJhUSFBwUJhUSFRIUHBUlFCYUExUAAa0jEhQlFRIWGxUkFhEWERYaFSUVJRUSFQANBQAAAAAAAAAAAAA="
              
#OK Button    
    lrmibox3_ok_button:
      sequence:
        - service: switch.broadlink_send_packet_172_16_10_252
          data:
            packet:
              - "JgBOACISFyMVEhQcFiQVEhUSFS8UHBUSFS8VAAGaIhMUJhQSFRwTJxQTFREWLhQcFRITMBUAAZsiEhUlFBMTHRUlFRIVEhQvFRsWERUuFwANBQAAAAAAAAAAAAA="
              
#Volume Up 
    lrmibox3_volume_up:
      sequence:
        - service: switch.broadlink_send_packet_172_16_10_252
          data:
            packet:
              - "JgBOACQQFSUVEhUbFSUVEhUSFS4VJhQTFBMUAAGuIhIVJRUSFRwTJhUSFRIVLhQmFBMTFBUAAa0jEhUlFRIUHBUlFBMUExQvFSUVEhURFQANBQAAAAAAAAAAAAA="
              
#Volume Down 
    lrmibox3_volume_down:
      sequence:
        - service: switch.broadlink_send_packet_172_16_10_252
          data:
            packet:
              - "JgBOACMRFSUVEhQcFSUVEhUSFS4VLhUSFRwVAAGbIhIVJBYRFRwUJRYRFRIWLhUvFBIVHBQAAZskERQmFBMUHBYkFRIUEhUvFC8VEhQcFQANBQAAAAAAAAAAAAA="
            
#Back Button 
    lrmibox3_back_button:
      sequence:
        - service: switch.broadlink_send_packet_172_16_10_252
          data:
            packet:
              - "JgBoACMRFiQUExQcFiQVEhYRFRsVLhUlFRwVAAGbIhIVJRURFhsVJRQTFRIWGhUvFCYUHBUAAZokERUlFRIUHBUlFBMUEhUcFC8VJRUbFQABmyMRFSUVEhQcFiQVEhUSFRsWLRUlFhsUAA0F"

#Exit Main Button
    lrmibox3_exit_main_button:
      sequence:
        - service: switch.broadlink_send_packet_172_16_10_252
          data:
            packet:
              - "JgBOACMSFSUVEhUbFSUVEhYQFhsVLhUmEx0VAAGbIhEVJRUSFB0VJRQTFBMUHBQvFSUVGxYAAZojEhMmFRIVHBQlFRIVEhUbFDAVJRcZFAANBQAAAAAAAAAAAAA="
              
#info Button
    lrmibox3_info_button:
      sequence:
        - service: switch.broadlink_send_packet_172_16_10_252
          data:
            packet:
              - "JgBoACMSEycUEhUcFCUWERYRFRwVJBUlFRIWAAGtIxEVJRUSFRsVJRUSFRIUHBQmFSUUExUAAa4hExUlFRIVGxQmFBMTFBMdFCYUJhQTFAABriMSEycUEhQdEycVERQTFRwVJBYkFhEVAA0F"

#media_player:
#  - platform: broadlink
#    name: LR Mi Box 3
#    host: 172.16.10.46
#    mac: '3c:bd:3e:73:7c:5e'
#    ircodes_ini: 'broadlink_media_codes/mibox3.ini'
#    ping_host: 172.16.10.46