###############################################################################
#   @author         :   Naty Laza
#   @date           :   04/01/2019
#   @package        :   Living Room TV Led Strip
#   @description    :   IR Commands Switch & Scripts & Automations, Sensors
#                       Input Select for Color & Mode
###############################################################################

####################################################
#                   Customize                      #
####################################################

homeassistant:
  customize_domain:
    automation:
      initial_state: 'on'
  
  customize:  
     switch.lrtv_stripled_power:
      friendly_name: "Strip Led Power"
      assumed_state: false
      icon: mdi:led-on

####################################################
#                      Switch                      #
####################################################

# Broadlink Configuration

switch:  
  - platform: broadlink
    host: !secret broadlink_host
    mac: !secret broadlink_mac
    friendly_name: rm
    type: rm
    timeout: 15
    switches:
#LR TV Strip Led
     lrtv_stripled_power:
      friendly_name: "Strip Led Power"
      command_on: 'JgBQAAABL5IWDxUQFhAVEBQSExIVERcPFTUVNBY0FjMWDxczFTUVNRcyFzQVERUQFg4XDxYPFRAWEBUQFzQVNRU1FTQWMxY0FgAFOwABLkgVAA0FAAAAAAAAAAA='
      command_off: 'JgBQAAABLpEVERcPFg4XDxYPFhAWDxUQFjQVNRU0FzMWEBY0FTUWMxYPFjQWDxYPFhAVEBURFRAWNBYQFTUWNBcyFjQVNRYzFgAFPgABL0cVAA0FAAAAAAAAAAA='

############################################################
#                         Sensors                          #
############################################################

sensor:
  - platform: template
    sensors:
#Living Room TV Led Strip Power State
       lrtv_ledstrip_status:
         value_template: >-
            {% if is_state('switch.lrtv_stripled_power', 'on') %}
               on
            {% else %}
               off
            {% endif %}
         friendly_name: 'LivingRoom TV Strip Led'  

####################################################
#                  Input Select                    #
####################################################

input_select:
#Living Room TV Led Strip Color Menu
 lrtv_stripled_color:
  name: lrtv_stripled_color
  icon: mdi:palette
  options:
    - RED
    - GREEN
    - BLUE
    - WHITE

#Living Room TV Led Strip Mode Menu
 lrtv_stripled_mode:
  name: lrtv_stripled_mode
  icon: mdi:led-strip
  options:
    - SMOOTH
    - FADE
    - STROBE
    - FLASH

####################################################
#                      Scripts                     #
####################################################

script:
#Power  
 ledlrtv_on:
  sequence:
    - service: switch.broadlink_send_packet_172_16_10_252
      data:
        packet:
              - "JgBQAAABL5IWDxUQFhAVEBQSExIVERcPFTUVNBY0FjMWDxczFTUVNRcyFzQVERUQFg4XDxYPFRAWEBUQFzQVNRU1FTQWMxY0FgAFOwABLkgVAA0FAAAAAAAAAAA="
              
 ledlrtv_off:
  sequence:
    - service: switch.broadlink_send_packet_172_16_10_252
      data:
        packet:
              - "JgBQAAABLpEVERcPFg4XDxYPFhAWDxUQFjQVNRU0FzMWEBY0FTUWMxYPFjQWDxYPFhAVEBURFRAWNBYQFTUWNBcyFjQVNRYzFgAFPgABL0cVAA0FAAAAAAAAAAA="
#Colors
 ledlrtv_red:
  sequence:
    - service: switch.broadlink_send_packet_172_16_10_252
      data:
        packet:
              - "JgBQAAABLpIXDxURFBETEhcQFg4WERUPFzMWNBY0FjQWDxY0FjQWNBUQFTUWNBUQFREVEBUSFQ8VNRURFg8VNRU1FTQYMxYzFwAFPgABLUkTAA0FAAAAAAAAAAA="
 ledlrtv_green:
  sequence:
    - service: switch.broadlink_send_packet_172_16_10_252
      data:
        packet:
              - "JgBQAAABMZAXDhcPFREWDxURFxATERURFDUWNBU1FzQVEBU1FTUVNRU1Fg4WNRYOFhIWDxURFRAVERU0FhAVNRYzFjMWNBU1FQAFPwABLkgVAA0FAAAAAAAAAAA="
 ledlrtv_blue:
  sequence:
    - service: switch.broadlink_send_packet_172_16_10_252
      data:
        packet:
              - "JgBYAAABLZIYDhcOFhAVEBYQFg8UEhMTFjQVNRU1FTUVEBU1FjMWNBYPFhAXMhYQFRAWEBUQFxAVNRM2FxAWNBU1FjIWNBU1FQAFQAABLkgXAAxSAAEwRxYADQU="
 ledlrtv_white:
  sequence:
    - service: switch.broadlink_send_packet_172_16_10_252
      data:
        packet:
              - "JgBQAAABL5IVERQSExIUEhMSFBIUERQSFDYUNRU1FTUUEhQ1FTUUNhQ2FDYUNhQRFREUERURFBEVERQRFREUNhQ2FDUUNhQ2FAAFQAABLUkUAA0FAAAAAAAAAAA="
#Modes
 ledlrtv_flash:
  sequence:
    - service: switch.broadlink_send_packet_172_16_10_252
      data:
        packet:
              - "JgBQAAABL5MVEBYOFw8VEBYQFRAWEBUQFTUVNRU0FzQWEBU0FjMVNRU1FTUVEBY0FRAVERUQFhAVEBcPFjQWDxYzFzMVNRU1FQAFPwABMUUXAA0FAAAAAAAAAAA="
 ledlrtv_strobe:
  sequence:
    - service: switch.broadlink_send_packet_172_16_10_252
      data:
        packet:
              - "JgBQAAABLpIWDxUQFhAXDxURFRAVEBYPFjUVNBYzFjQVERU0FjQVNRc0FTUVNRU0Fg8WEBYPFg8UEhMSFxAVEBY0FTUVNRU0FgAFPwABL0YXAA0FAAAAAAAAAAA="
 ledlrtv_fade:
  sequence:
    - service: switch.broadlink_send_packet_172_16_10_252
      data:
        packet:
              - "JgBQAAABL5EYDxUQFhAWDhYQFg8WEBcPFjQVNRU1FjMWDxY0FjQWNBU0FzMXDxYPFDYXEBYOFhEVDxYPFzMWNBURFTQWNBY0FQAFPAABMEYXAA0FAAAAAAAAAAA="
 ledlrtv_smooth:
  sequence:
    - service: switch.broadlink_send_packet_172_16_10_252
      data:
        packet:
              - "JgBYAAABMJEXEBYOFw8WDxYQFg8XEBUPFzQVNRU1FjMWDxY0FjQVNRU0GDMWNBYPFjMWEBUQFhAVEBURFRAXNBUQFjQWMxY0FgAFPwABMEcWAAxMAAEvRxUADQU="

#Living Room TV Led Strip Color Toggle Script
 lrtv_stripled_color:
  sequence:
    - service_template: >
          {% if is_state('input_select.lrtv_stripled_color', 'RED') %} script.ledlrtv_red
          {% elif is_state('input_select.lrtv_stripled_color', 'GREEN') %} script.ledlrtv_green
          {% elif is_state('input_select.lrtv_stripled_color', 'BLUE') %} script.ledlrtv_blue
          {% elif is_state('input_select.lrtv_stripled_color', 'WHITE') %} script.ledlrtv_white
          {% endif %}

#Living Room TV Led Strip Mode Toggle Script
 lrtv_stripled_mode:
  sequence:
    - service_template: >
          {% if is_state('input_select.lrtv_stripled_mode', 'SMOOTH') %} script.ledlrtv_smooth
          {% elif is_state('input_select.lrtv_stripled_mode', 'FADE') %} script.ledlrtv_fade
          {% elif is_state('input_select.lrtv_stripled_mode', 'STROBE') %} script.ledlrtv_strobe
          {% elif is_state('input_select.lrtv_stripled_mode', 'FLASH') %} script.ledlrtv_flash
          {% endif %}

####################################################
#                   Automations                    #
####################################################

automation:

#Runs when Input Select lrtv_stripled_color get toggeled
- id: lrtv_stripled_color_select_toggle
  alias: lrtv_stripled_color_select_toggle
  trigger:
  - platform: state
    entity_id: input_select.lrtv_stripled_color
  action:
  - service: script.lrtv_stripled_color

#Runs when Input Select lrtv_stripled_mode get toggeled
- id: lrtv_stripled_mode_select_toggle
  alias: lrtv_stripled_mode_select_toggle
  trigger:
  - platform: state
    entity_id: input_select.lrtv_stripled_mode
  action:
  - service: script.lrtv_stripled_mode