###############################################################################
#   @author         :   Naty Laza
#   @date           :   23/03/2019
#   @package        :   Alexa Anouncment
#   @description    :   Welcome Home, Shopping etc.
###############################################################################

####################################################
#                   Customize                      #
####################################################

homeassistant:
  customize_domain:
    automation:
      initial_state: 'on'
  
  customize:

####################################################
#                    Automation                    #
####################################################

automation:

###################
#       Naty      #
###################

- id: Alexa Anounced Welcome Naty Home
  alias: Alexa Anounced Welcome Naty Home
  trigger:
  - entity_id: sensor.naty_current_status
    platform: state
    to: 'Home'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: binary_sensor.naty_mia1_connectivity
        state: 'on'
      - condition: time
        before: '22:00:00'
        after: '8:00:00'
  action:
  - delay: 00:00:20
  - service: media_player.alexa_tts 
    entity_id: media_player.naty_s_echo_dot
    data:
        message: "Welcome Home Naaty"

# hezi hinam announcement
- id: Alexa Anounced that Naty at hazihinam
  alias: Alexa Anounced that Naty at hazihinam
  trigger:
  - entity_id: device_tracker.naty
    platform: state
    to: 'Hazi Hinam'
    for:
     minutes: 10
  condition:
  - condition: state
    entity_id: device_tracker.nofar
    state: 'home'
  action:
  - service: media_player.alexa_tts 
    entity_id: media_player.naty_s_echo_dot
    data:
        message: "Naaty is at Haatzi Heenaame doing shopping"
        
# Shufersal announcement
- id: Alexa Anounced that Naty at shufersal
  alias: Alexa Anounced that Naty at shufersal
  trigger:
  - entity_id: device_tracker.naty
    platform: state
    to: 'Shufersal'
    for:
     minutes: 10
  condition:
  - condition: state
    entity_id: device_tracker.nofar
    state: 'home'
  action:
  - service: media_player.alexa_tts 
    entity_id: media_player.naty_s_echo_dot
    data:
        message: "Naaty is at shufersaal doing shopping"  
        
####################
#       Nofar      #
####################

- id: Alexa Anounced Welcome Nofar Home
  alias: Alexa Anounced Welcome Nofar Home
  trigger:
  - entity_id: sensor.nofar_current_status
    platform: state
    to: 'Home'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: binary_sensor.nofar_oneplus5t_connectivity
        state: 'on'
      - condition: time
        before: '22:00:00'
        after: '8:00:00'
  action:
  - delay: 00:00:20
  - service: media_player.alexa_tts 
    entity_id: media_player.naty_s_echo_dot
    data:
        message: "Welcome Home Nofar"

# Nofar at hezi hinam announcement
- id: Alexa Anounced that Nofar at hazihinam
  alias: Alexa Anounced that Nofar at hazihinam
  trigger:
  - entity_id: device_tracker.nofar
    platform: state
    to: 'Hazi Hinam'
    for:
     minutes: 10
  condition:
  - condition: state
    entity_id: device_tracker.naty
    state: 'home'
  action:
  - service: media_player.alexa_tts 
    entity_id: media_player.naty_s_echo_dot
    data:
        message: "Nofar is at Haatzi Heenaame doing shopping"
        
# Nofar at shufersal announcement
- id: Alexa Anounced that Nofar at shufersal
  alias: Alexa Anounced that Nofar at shufersal
  trigger:
  - entity_id: device_tracker.nofar
    platform: state
    to: 'Shufersal'
    for:
     minutes: 10
  condition:
  - condition: state
    entity_id: device_tracker.naty
    state: 'home'
  action:
  - service: media_player.alexa_tts 
    entity_id: media_player.naty_s_echo_dot
    data:
        message: "Nofar is at shufersaal doing shopping"
