###############################################################################
#   @author         :   Naty Laza
#   @date           :   21/03/2019
#   @package        :   Alexa Configuration
#   @description    :   Cloud Configuration of Alexa
###############################################################################

####################################################
#               Alexa as Media Player              #
####################################################


alexa_media:
  accounts:
    email: !secret amazon_email
    password: !secret amazon_password
    url: !secret amazon_url

####################################################
#               Alexa Configuration                #
####################################################

#cloud:
alexa:
    smart_home:
      endpoint: https://api.amazonalexa.com/v3/events
      client_id: !secret alexa_client_id
      client_secret: !secret alexa_client_secret
      filter:
        include_entities: 
          - alarm_control_panel.home_alarm
          - climate.living_room
          - fan.bedroom_fan 
          - light.gateway_light_7811dcf781f1
          - light.yeelight_mono1_f0b4290eb30b
          - media_player.natys_echo_dot
          - media_player.mibox3
        include_domains:
          - switch
          - script
          - lights
        exclude_entities:
          - media_player.natys_alexa_apps
          - media_player.kodi
          - media_player.this_device
        exclude_domains:
          - device_tracker
          - automation
          - binary_sensor
          - calendar
          - customizer
          - group
          - input_boolean
          - input_select
          - input_text
          - sensor
          - zone
          - sun

  #Customize Entities as will be shown in alexa app
      entity_config:
  #Bed Room      
        switch.brfan_light:
          name: Fan Light
          description: BR Fan Light Power
        script.bed_room_fan_mode:
          name: Fan Mode
          description: BR Fan Mode
        fan.bedroom_fan:
          name: Bed Room Fan
          description: Bed Room Fan 
  #Living Room
        switch.lrac_power:
          name: AC Power
          description: LR AC Power
        switch.lrmibox_power:
          name: Mi Box  
          description: Mi Box Power
        switch.lrtv_mute:
          name: Mute TV
          description: Mute LR TV
        switch.lrtv_power: 
          name: TV
          description: LR TV Power
        switch.lrtv_stripled_power:
          name: Strip Led
          description: LR TV Strip Led Power
        switch.xiaomi_plug: 
          name: Smart Plug 
          description: Xiaomi Smart Plug
        script.lrtv_volume_up:
          name: TV Volume UP               
          description: LR TV Volume UP 
        script.lrtv_volume_down:
          name: TV Volume Down
          description: LR TV Volume Down 
        script.temp_up:
          name: Temp UP
          description: LR AC Temp UP
        script.temp_down:
          name: Temp Down
          description: LR AC Temp
        script.lrmibox3_volume_up:
          name: Mi Box Volume UP
          description: Mi Box Volume UP
        script.lrmibox3_volume_down:
          name: Mi Box Volume Down
          description: Mi Box Volume Down   
        light.gateway_light_7811dcf781f1:
          name: Gateway Light
          description: Gateway Light
        climate.living_room:
          name: Living Room Air Conditioner
          description: Living Room Air Conditioner
        media_player.natys_echo_dot:
          name: Echo Dot
          description: Echo Dot
  #Alarm Control  
        alarm_control_panel.home_alarm:
          name: Alarm
          description: Alarm
    #Work Room
        light.yeelight_mono1_f0b4290eb30b:
          name: Office Light
          description: Office Light

    #Away Mode
        script.away_mode_toggle:
          name: Away Mode Toggle
          description: Away Mode Toggle

    #Switcher V2/Boiler
        script.boiler_60_minutes:
          name: Boiler 60 Minutes
          description: Boiler 60 Minutes
        script.boiler_45_minutes:
          name: Boiler 45 Minutes
          description: Boiler 45 Minutes
        script.boiler_30_minutes:
          name: Boiler 30 Minutes
          description: Boiler 30 Minutes
        script.boiler_15_minutes:
          name: Boiler 15 Minutes
          description: Boiler 15 Minutes
        