###############################################################################
#   @author         :   Naty Laza
#   @date           :   31/10/2018
#   @description    :   Main Configuration
###############################################################################

homeassistant:
  name: Naty Home Assistant
  latitude: !secret homeassistant_latitude
  longitude: !secret homeassistant_longitude
  elevation: !secret homeassistant_elevation
  temperature_unit: C
  unit_system: metric
  time_zone: Asia/Jerusalem
  auth_providers:
   - type: homeassistant
#   - type: legacy_api_password
  packages: !include_dir_named packages

###############################################################################################################################################
updater:                                         # for HA Update Available Notification
custom_updater:                                  # A component which allows you to track and update custom cards/components and python_scripts.
discovery:                                       # Discovers Devices on your network.
conversation:                                    # Use tts over supported Browsers
sun:                                             # Track the sun
map:                                             # Enables a map which shows tracked devices
python_script:                                   # Enable the abillity of using python scripts
config:                                          # Enables configuration UI
system_health:                                   # Information on the system and it’s components
shopping_list:
###############################################################################################################################################