###############################################################################
#   @author         :   Naty Laza
#   @date           :   28/10/2018
#   @description    :   Secrets
###############################################################################

####################################################
#                        HTTP                      #
####################################################

api_password: password
base_url: user.duckdns.org
private_lan: x.x.x.x

####################################################
#                        SSL                       #
####################################################

ssl_certificate_dir: '/etc/letsencrypt/live/user.duckdns.org/fullchain.pem'
ssl_key_dir: '/etc/letsencrypt/live/user.duckdns.org/privkey.pem'
renew_ssl_command: ~/letsencrypt/certbot-auto renew --quiet --no-self-upgrade --standalone --preferred-challenges http-01
sensor_ssl_command: "ssl-cert-check -b -c /etc/letsencrypt/live/user.duckdns.org/cert.pem | awk '{ print $NF }'"

####################################################
#                     DuckDNS                      #
####################################################
duckdns_domain: username
duckdns_access_token: token

####################################################
#                influxdb Database                 #
#################################################### 

influxdb_url: x.x.x.x
influxdb_username: user
influxdb_password: password

####################################################
#                     Broadlink                    #
####################################################
broadlink_host: x.x.x.x
broadlink_mac: 'xx:xx:xx:xx:xx:xx'

####################################################
#             Xiaomi Aqara & Alarm                 #
####################################################
aqara_key: token
aqara_gw_mac: xx:xx:xx:xx:xx:xx
alarm_code: 1234

####################################################
#                     Unifi                        #
####################################################
unifi_username: username
unifi_password: password
unif_url: https://x.x.x.x:8443

####################################################
#                 Network Sensors                  #
####################################################
router_ip_sensor: x.x.x.x
uap_ip_sensor: x.x.x.x
rmpro_ip_sensor: x.x.x.x
rpi3_ip_sensor: x.x.x.x
mibox3_ip_sensor: x.x.x.x
echo_ip_sensor: x.x.x.x
gateway_ip_sensor: x.x.x.x

####################################################
#                     Telegram Bot                 #
####################################################
telegram_api_key: api_token
telegram_naty_id: id
telegram_nofar_id: id
telegram_mipad_id: id

####################################################
#                     Google API                   #
####################################################
#Google Calendar
google_calendar_client_id: google_token
google_calendar_client_secret: secret

####################################################
#                 Echo dot - Alexa                 #
####################################################
amazon_email: email
amazon_password: password
amazon_url: amazon.com

####################################################
#                       Zones                      #
####################################################
homeassistant_latitude: number
homeassistant_longitude: number
homeassistant_elevation: number
Ashkelon_latitude: number
Ashkelon_longitude: number
Natanya_latitude: number
Natanya_longitude: number
College_latitude: number
College_longitude: number
Home_latitude: number
Home_longitude: number
Nofar_Work_latitude: number
Nofar_Work_longitude: number
Hazi_Hinam_latitude: number
Hazi_Hinam_longitude: number
Shufersal_latitude: number
Shufersal_longitude: number

####################################################
#                       MQTT                       #
####################################################
mqtt_user: username
mqtt_password: password
mqtt_port: 1883
broker_ip: x.x.x.x

####################################################
#               TrackR Device Tracker              #
####################################################
trackr_user: email
trackr_password: password

####################################################
#                     Birthday                     #
####################################################
nofar_birthday: "DATE=`date -d 'Jan 1' +%j | awk '{print $1 + 0}'`; TODAY=`date +%j | awk '{print $1 + 0}'`; if [ $DATE -ge $TODAY ]; then DAYS=$(($DATE - $TODAY));else DAYS=$(($DATE - $TODAY + 365)); fi; echo $DAYS"
naty_birthday: "DATE=`date -d 'Jan 1' +%j | awk '{print $1 + 0}'`; TODAY=`date +%j | awk '{print $1 + 0}'`; if [ $DATE -ge $TODAY ]; then DAYS=$(($DATE - $TODAY));else DAYS=$(($DATE - $TODAY + 365)); fi; echo $DAYS"
matan_birthday: "DATE=`date -d 'Jan 1' +%j | awk '{print $1 + 0}'`; TODAY=`date +%j | awk '{print $1 + 0}'`; if [ $DATE -ge $TODAY ]; then DAYS=$(($DATE - $TODAY));else DAYS=$(($DATE - $TODAY + 365)); fi; echo $DAYS"
moshe_birthday: "DATE=`date -d 'Jan 1' +%j | awk '{print $1 + 0}'`; TODAY=`date +%j | awk '{print $1 + 0}'`; if [ $DATE -ge $TODAY ]; then DAYS=$(($DATE - $TODAY));else DAYS=$(($DATE - $TODAY + 365)); fi; echo $DAYS"
sarah_birthday: "DATE=`date -d 'Jan 1' +%j | awk '{print $1 + 0}'`; TODAY=`date +%j | awk '{print $1 + 0}'`; if [ $DATE -ge $TODAY ]; then DAYS=$(($DATE - $TODAY));else DAYS=$(($DATE - $TODAY + 365)); fi; echo $DAYS"
